version: "3.7"

services:
  item-service:
    restart: always
    build: ./item-service
    ports:
      - 8081:8081
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/
  order-service:
    restart: always
    build: ./order-service
    ports:
      - 8082:8082
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
  user-service:
    restart: always
    build: ./user-service
    ports:
      - 8083:8083
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
  discovery-server:
    restart: always
    build: ./discovery-server
    ports:
      - 8761:8761
  
  user-database:
    restart: always
    image: postgres:12.2
    ports:
        - ${USER_DB_PORT}:5432
    environment:
        POSTGRES_DB: ${USER_DB_DATABASE}
        POSTGRES_USER: ${USER_DB_USER}
        POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
        
  order-database:
    restart: always
    image: postgres:12.2
    ports:
        - ${ORDER_DB_PORT}:5432
    environment:
        POSTGRES_DB: ${ORDER_DB_DATABASE}
        POSTGRES_USER: ${ORDER_DB_USER}
        POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}

  item-database:
    restart: always
    image: postgres:12.2
    ports:
        - ${ITEM_DB_PORT}:5432
    environment:
        POSTGRES_DB: ${ITEM_DB_DATABASE}
        POSTGRES_USER: ${ITEM_DB_USER}
        POSTGRES_PASSWORD: ${ITEM_DB_PASSWORD}
