version: "3.7"

services:
  item-service:
    restart: always
    build: ./item-service
    ports:
      - 8081:8081
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/
  order-service:
    restart: always
    build: ./order-service
    ports:
      - 8082:8082
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
  user-service:
    restart: always
    build: ./user-service
    ports:
      - 8083:8083
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
  discovery-server:
    restart: always
    build: ./discovery-server
    ports:
      - 8761:8761
  database:
    restart: always
    image: postgres:12.2
    ports:
        - ${DB_PORT}:5432
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
