server:
  port: 8083

spring:
  application:
    name: user-service
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${USER_DB_HOST}:${USER_DB_PORT}/${USER_DB_DATABASE}
    username: ${USER_DB_USER} 
    password: ${USER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver