server:
  port: 8082

spring:
  application:
    name: order-service
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER} 
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
