server:
  port: 8082

spring:
  application:
    name: order-service
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${ORDER_DB_HOST}:${ORDER_DB_PORT}/${ORDER_DB_DATABASE}
    username: ${ORDER_DB_USER} 
    password: ${ORDER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
