server:
  port: 8081

spring:
  application:
    name: item-service
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://${ITEM_DB_HOST}:${ITEM_DB_PORT}/${ITEM_DB_DATABASE}
    username: ${ITEM_DB_USER} 
    password: ${ITEM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
